package com.techelevator;
import java.util.Scanner; //imported java.util.Scanner to access Scanner Class

//public class for main method
public class Fibonacci {

	//method is public (can be accessed outside the class, static means the method belongs to the class, return type is void (nothing to return)
	//variables is a String array
	public static void main(String[] args) {

		//These variables are used for the Fibonacci calculation
		//Created an int variable called firstFib and initialized it to 0;
		int firstFib = 0;
		//Created new scanner variable named input to take in user input
		Scanner input = new Scanner(System.in);
		//Told the system to output a mesasge to the user to enter an integer
		System.out.print("Please enter an integer: ");
		//Created an int variable called getNumb and stores/initializes the value of the (next) input as an integer
		int getNumb = input.nextInt();
		//Told the system to store the last entered value in the input variable
		input.nextLine();
		//Created an if statement to account for when the getNumb is equal to 0 or less
		if (getNumb <= 0) {
			//System prints outs 0 ,1 if this condition is met
			System.out.print("0, 1");
		//Created an else statement when the above IF condition is not met (any other scenario besides 0 or negative number)
		} else {
			//Created an int variable called secondFib and initialized it to firstFib value;
			int secondFib = firstFib;
			//System prints out 0 + an empty string (space) when the above IF Condition is not met
			//The empty string creates space from the 0 for the output that will be generated by the FOR loop
			System.out.print(0 + " ");
			//Created FOR loop to determine what output should be displayed when the user enters a positive integer
			//Initialized the FOR loop at 1 because 0 and negatives are covered in the IF statement,
			//set the condition to loop until the getNumb (user input) is equal to or greater than the nextNum variable
			for (int nextNumb = 1; nextNumb <= getNumb;) {
				//Told the system to print out value of the nextNum variable + an empty string (space)
				System.out.print(nextNumb + " ");
				//Set the keepInitial variable to initial (Ex. x = 1)
				secondFib = firstFib;
				//Set the initial variable to nextNum (Ex. x = 1)
				firstFib = nextNumb;
				//fibonacci calculation - set the  nextNumb variable equal to the nextNumb value + secondFib value (Ex. x = x + 1)
				nextNumb += secondFib;
			}
		}
	}
}


